import Card from '../../../ui/components/Card'
const groups:[string,string[]][]=[['Процессы',['процессы','processes']],['Системы',['системы','systems']],['Роли',['роли','roles']],['Интеграции',['интеграции','integrations']],['KPI',['kpi']],['Ограничения',['constraints','ограничения']],['Ключевые сущности',['бизнес_сущности','business_entities']],['Документы',['документы','documents']],['Термины',['термины','terms']]]

export default function ExtractedKnowledgeCard({knowledge,sourceTrace=[]}:{knowledge:any;sourceTrace?:any[]}){
  const emptyMajor=groups.every(([,keys])=>keys.filter(k=>!['documents','документы'].includes(k)).flatMap(k=>Array.isArray(knowledge?.[k])?knowledge[k]:[]).length===0)
  const missing=(knowledge?.missing_information||[]).slice(0,8)
  const trace=sourceTrace.length?sourceTrace:(knowledge?.source_trace||[])
  const metadataOnly=trace.length>0 && trace.every((s:any)=>s.content_level==='metadata_only')
  return <Card title='Извлечённые знания'>{!knowledge?<p className='sub'>AI пока не извлёк знания. Нажмите «Обновить контекст».</p>:<>{metadataOnly&&emptyMajor&&<div className='hint-card'><b>Знания почти не извлечены.</b><p>Документы/ссылки доступны только как метаданные. Для полного анализа нужен извлечённый текст или ручное описание.</p></div>}{groups.map(([label,keys])=>{const items=keys.flatMap(k=>Array.isArray(knowledge?.[k])?knowledge[k]:[]);return <div key={label} className='knowledge-group'><div className='knowledge-group__title'>{label} ({items.length})</div><div className='knowledge-pills'>{items.slice(0,8).map((x:any,i:number)=><span className='knowledge-pill' key={i}>{String(x)}</span>)}</div></div>})}{missing.length>0&&<div className='hint-card'><b>Чего не хватает</b><ul>{missing.map((m:string,i:number)=><li key={i}>{m}</li>)}</ul></div>}{trace.length>0&&<div className='hint-card'><b>Source trace</b><ul>{trace.slice(0,6).map((s:any,i:number)=><li key={i}>{s.used?'Использован':'Не использован'} · {s.source_name||s.source_id} · {s.content_level}</li>)}</ul></div>}</>}</Card>
}
