import { File, FileSpreadsheet, FileText, Link2, Trash2, UploadCloud } from 'lucide-react'
import Button from '../../../ui/components/Button'
import Card from '../../../ui/components/Card'

type Props={documents:any[];links:any[];sourceTrace:any[];onAddLink:()=>void;linkDraft:string;setLinkDraft:(v:string)=>void;onUpload:(e:any)=>void;onDeleteDocument:(i:number)=>void;onDeleteLink:(i:number)=>void}
const fileIcon=(name:string)=>name.endsWith('.xlsx')||name.endsWith('.xls')?'xls':name.endsWith('.doc')||name.endsWith('.docx')?'doc':'pdf'
export default function KnowledgeSourcesCard({documents,links,sourceTrace,onAddLink,linkDraft,setLinkDraft,onUpload,onDeleteDocument,onDeleteLink}:Props){
  const findTrace=(sourceType:string,id:string)=>sourceTrace?.find((x:any)=>x.source_type===sourceType && String(x.source_id)===String(id))
  const docStatus=(d:any,tr:any)=>{const st=d?.text_extraction_status; if(st==='completed') return 'Текст извлечён'; if(st==='unsupported') return 'Формат не поддержан'; if(st==='failed') return 'Ошибка извлечения'; if(st==='empty') return 'Текст не найден'; if(st==='not_available') return 'Только метаданные'; return tr?.content_level==='metadata_only'?'Только метаданные':tr?.used?'Проиндексирован':'Нет текста'}
  const linkStatus=(l:any,tr:any)=>tr?.content_level==='metadata_only'?'Только URL':tr?.used?'Проиндексирована':'Нет содержимого'
  return <Card title='Источники знаний'>
    <div className='source-section'><div className='source-section__header'><div className='source-section__title'>Документы ({documents.length})</div><label className='ui-btn ui-btn--secondary ui-btn--sm'><UploadCloud size={14}/>Загрузить файлы<input type='file' multiple className='hidden-input' onChange={onUpload}/></label></div><div className='source-list'>{documents.map((d:any,i:number)=>{const t=fileIcon(d?.name||''); const id=d?.id||`doc_${i}`; const tr=findTrace('document',id); const badge=docStatus(d,tr); const tip=d?.text_extraction_status==='unsupported'&&String(d?.name||'').toLowerCase().endsWith('.pdf')?'Текст из PDF пока не извлекается':d?.text_extraction_status==='unsupported'?'Текст из XLSX пока не извлекается':''; return <div className='source-row' key={i}><div className={`source-icon source-icon--${t}`}>{t==='xls'?<FileSpreadsheet size={16}/>:t==='doc'?<FileText size={16}/>:<File size={16}/>}</div><div className='source-main'><div className='source-title'>{d?.name||'Без названия'}</div><div className='source-meta'>{d?.size||0} · Загружен {d?.created_at?new Date(d.created_at).toLocaleDateString('ru-RU'):'—'}{tip?` · ${tip}`:''}</div></div><span className='ui-badge warning'>{badge}</span><Button variant='icon' size='sm' aria-label='Удалить файл' onClick={()=>onDeleteDocument(i)}><Trash2 size={14}/></Button></div>})}</div></div>
    <div className='source-section'><div className='source-section__header'><div className='source-section__title'>Ссылки ({links.length})</div></div><div className='source-list'>{links.map((l:any,i:number)=>{const id=l?.id||`link_${i}`; const tr=findTrace('link',id); const badge=linkStatus(l,tr); return <div className='source-row' key={i}><div className='source-icon source-icon--link'><Link2 size={16}/></div><div className='source-main'><div className='source-title'>{String(l?.url||l)}</div><div className='source-meta'>{l?.type||'Ссылка'}</div></div><span className='ui-badge warning'>{badge}</span><Button variant='icon' size='sm' aria-label='Удалить ссылку' onClick={()=>onDeleteLink(i)}><Trash2 size={14}/></Button></div>})}</div><div className='ui-actions'><input className='ui-input' placeholder='Добавить ссылку...' value={linkDraft} onChange={e=>setLinkDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter') onAddLink()}}/><Button variant='primary' size='sm' onClick={onAddLink}>Добавить ссылку</Button></div></div>
  </Card>
}
