import { File, FileSpreadsheet, FileText, Link2, Trash2, UploadCloud } from 'lucide-react'
import Button from '../../../ui/components/Button'
import Card from '../../../ui/components/Card'

type Props={documents:any[];links:any[];onAddLink:()=>void;linkDraft:string;setLinkDraft:(v:string)=>void;onUpload:(e:any)=>void;onDeleteDocument:(i:number)=>void;onDeleteLink:(i:number)=>void}
const fileIcon=(name:string)=>name.endsWith('.xlsx')||name.endsWith('.xls')?'xls':name.endsWith('.doc')||name.endsWith('.docx')?'doc':'pdf'
export default function KnowledgeSourcesCard({documents,links,onAddLink,linkDraft,setLinkDraft,onUpload,onDeleteDocument,onDeleteLink}:Props){
  return <Card title='Источники знаний'>
    <div className='source-section'><div className='source-section__header'><div className='source-section__title'>Документы ({documents.length})</div><label className='ui-btn ui-btn--secondary ui-btn--sm'><UploadCloud size={14}/>Загрузить файлы<input type='file' multiple className='hidden-input' onChange={onUpload}/></label></div><div className='source-list'>{documents.map((d:any,i:number)=>{const t=fileIcon(d?.name||'');return <div className='source-row' key={i}><div className={`source-icon source-icon--${t}`}>{t==='xls'?<FileSpreadsheet size={16}/>:t==='doc'?<FileText size={16}/>:<File size={16}/>}</div><div className='source-main'><div className='source-title'>{d?.name||'Без названия'}</div><div className='source-meta'>{d?.size||0} · Загружен {d?.created_at?new Date(d.created_at).toLocaleDateString('ru-RU'):'—'}</div></div><span className='ui-badge ready'>Проиндексирован</span><Button variant='icon' size='sm' aria-label='Удалить файл' onClick={()=>onDeleteDocument(i)}><Trash2 size={14}/></Button></div>})}</div></div>
    <div className='source-section'><div className='source-section__header'><div className='source-section__title'>Ссылки ({links.length})</div></div><div className='source-list'>{links.map((l:any,i:number)=><div className='source-row' key={i}><div className='source-icon source-icon--link'><Link2 size={16}/></div><div className='source-main'><div className='source-title'>{String(l?.url||l)}</div><div className='source-meta'>{l?.type||'Ссылка'}</div></div><span className='source-type'>{l?.type||'link'}</span><Button variant='icon' size='sm' aria-label='Удалить ссылку' onClick={()=>onDeleteLink(i)}><Trash2 size={14}/></Button></div>)}</div><div className='ui-actions'><input className='ui-input' placeholder='Добавить ссылку...' value={linkDraft} onChange={e=>setLinkDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter') onAddLink()}}/><Button variant='primary' size='sm' onClick={onAddLink}>Добавить</Button></div></div>
  </Card>
}
