import { File, FileSpreadsheet, FileText, Link2, RefreshCcw, Trash2, UploadCloud } from 'lucide-react'
import Button from '../../../ui/components/Button'
import Card from '../../../ui/components/Card'

type Props={documents:any[];links:any[];sourceTrace:any[];onAddLink:()=>void;linkDraft:string;setLinkDraft:(v:string)=>void;onUpload:(e:any)=>void;onDeleteDocument:(i:number)=>void;onDeleteLink:(i:number)=>void;onRetryIndex?:()=>void}
const fileIcon=(name:string)=>name.endsWith('.xlsx')||name.endsWith('.xls')?'xls':name.endsWith('.doc')||name.endsWith('.docx')?'doc':'pdf'
const badgeVariant=(status:string)=>status==='ready'||status==='completed'?'ready':status==='error'||status==='failed'||status==='unsupported'?'error':status==='indexing'?'progress':'warning'
const formatSize=(size:any)=>{const n=Number(size||0); if(!n) return '0 B'; if(n<1024) return `${n} B`; if(n<1024*1024) return `${(n/1024).toFixed(1)} KB`; return `${(n/1024/1024).toFixed(1)} MB`}
export default function KnowledgeSourcesCard({documents,links,sourceTrace,onAddLink,linkDraft,setLinkDraft,onUpload,onDeleteDocument,onDeleteLink,onRetryIndex}:Props){
  const findTrace=(sourceType:string,id:string)=>sourceTrace?.find((x:any)=>x.source_type===sourceType && String(x.source_id)===String(id))
  const docStatus=(d:any,tr:any)=>{if(d?.status==='indexing') return 'Индексируется'; if(d?.status==='ready') return 'Готово'; if(d?.status==='error') return 'Ошибка'; const st=d?.text_extraction_status; if(st==='completed') return 'Текст извлечён'; if(st==='unsupported') return 'Формат не поддержан'; if(st==='failed') return 'Ошибка извлечения'; if(st==='empty') return 'Текст не найден'; if(st==='not_available') return 'Только метаданные'; return tr?.content_level==='metadata_only'?'Только метаданные':tr?.used?'Проиндексирован':'Загружено'}
  const linkStatus=(l:any,tr:any)=>l?.status==='error'?'Ошибка':tr?.content_level==='metadata_only'?'Только URL':tr?.used?'Проиндексирована':'Загружено'
  const isEmpty=!documents.length&&!links.length
  return <Card title='Источники знаний'>
    <div className='hint-card'><b>Что лучше загрузить</b><p>BRD, описания процессов, регламенты, выгрузки CSV/XLSX, TXT/MD заметки, ссылки на Jira/Confluence/Figma/BI. Для DOCX/TXT/MD/CSV текст извлекается автоматически; PDF/XLSX сохраняются как источник и требуют дальнейшего извлечения.</p></div>
    {isEmpty&&<div className='empty-context-state'><b>Контекст ещё не добавлен</b><p className='sub'>Добавьте документы или ссылки, затем нажмите «Обновить контекст», чтобы AI сформировал выжимку для следующего этапа.</p></div>}
    <div className='source-section'><div className='source-section__header'><div className='source-section__title'>Документы ({documents.length})</div><div className='ui-actions'><Button variant='secondary' size='sm' onClick={onRetryIndex}><RefreshCcw size={14}/>Повторить индексацию</Button><label className='ui-btn ui-btn--secondary ui-btn--sm'><UploadCloud size={14}/>Загрузить файлы<input type='file' multiple className='hidden-input' onChange={onUpload}/></label></div></div><div className='source-list'>{documents.map((d:any,i:number)=>{const t=fileIcon(String(d?.name||d?.fileName||d?.title||'')); const id=d?.id||`doc_${i}`; const tr=findTrace('document',id); const badge=docStatus(d,tr); const tip=d?.errorMessage||d?.text_extraction_error||''; return <div className='source-row' key={id}><div className={`source-icon source-icon--${t}`}>{t==='xls'?<FileSpreadsheet size={16}/>:t==='doc'?<FileText size={16}/>:<File size={16}/>}</div><div className='source-main'><div className='source-title'>{d?.title||d?.name||d?.fileName||'Без названия'}</div><div className='source-meta'>{formatSize(d?.size)} · Чанков: {d?.chunksCount??(Array.isArray(d?.chunks)?d.chunks.length:0)} · Загружен {d?.createdAt||d?.created_at?new Date(d.createdAt||d.created_at).toLocaleDateString('ru-RU'):'—'}{tip?` · ${tip}`:''}</div></div><span className={`ui-badge ${badgeVariant(d?.status||d?.text_extraction_status)}`}>{badge}</span><Button variant='icon' size='sm' aria-label='Удалить файл' onClick={()=>onDeleteDocument(i)}><Trash2 size={14}/></Button></div>})}</div></div>
    <div className='source-section'><div className='source-section__header'><div className='source-section__title'>Ссылки ({links.length})</div></div><div className='source-list'>{links.map((l:any,i:number)=>{const id=l?.id||`link_${i}`; const tr=findTrace('link',id); const badge=linkStatus(l,tr); return <div className='source-row' key={id}><div className='source-icon source-icon--link'><Link2 size={16}/></div><div className='source-main'><div className='source-title'>{String(l?.url||l)}</div><div className='source-meta'>{l?.type||'Ссылка'} · {l?.errorMessage||'Содержимое страницы пока не скачивается автоматически'}</div></div><span className={`ui-badge ${badgeVariant(l?.status)}`}>{badge}</span><Button variant='icon' size='sm' aria-label='Удалить ссылку' onClick={()=>onDeleteLink(i)}><Trash2 size={14}/></Button></div>})}</div><div className='ui-actions'><input className='ui-input' placeholder='Добавить ссылку...' value={linkDraft} onChange={e=>setLinkDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter') onAddLink()}}/><Button variant='primary' size='sm' onClick={onAddLink}>Добавить ссылку</Button></div></div>
  </Card>
}
